---
title: "ANNs_VoterTurnout_Data_Pipeline"
author: "Juan Pablo"
date: "2024-11-11"
output: html_document
---



```{r}
# libraries 

# loading
library(tidyverse)
library(here)
library(httr)
library(jsonlite)
library(xml2)


# set directory
here::i_am("code/ANNs_VoterTurnout_Data_Pipeline.Rmd")


```




# Section One - API Census Data Fetching

```{r}
# US Census Board API Key
# 6b04ff55736c418eed28d02b041d8a382d5b0319
USCB_APIkey <- "6b04ff55736c418eed28d02b041d8a382d5b0319"



# FUNCTION: API FETCH and SAVE --------------------------------------------------------

apifetch_censusdata <- function(variable, year, key) {
  print(paste0("fetching: ", year, "-", variable))
  
  # construct the URL with the variable, year, and key dynamically
  url <- paste0("https://api.census.gov/data/", 
                year, 
                "/acs/acs5/profile?get=", 
                variable, 
                "&for=county:*&key=", 
                key)
  
  

  # make the API request
  response <- GET(url)
  # parse the JSON response
  data <- content(response, 
                  as = "text", 
                  encoding = "UTF-8")
  json_data <- fromJSON(data)
  
  # convert the JSON data to a dataframe
  df <- as.data.frame(json_data[-1, ])  # Skip the first row (header)
  colnames(df) <- json_data[1, ]  # Assign the first row as column names
  # create a dynamic filename based on the variable and year
  file_name <- paste0(here("data/raw/api_censusdata/"), variable, "_", year, ".csv")
  # save the dataframe as a CSV file
  write.csv(df, file_name, row.names = FALSE)
  
  print(paste0("Saved:", 
      variable,
      "_",
      year,
      ".csv")) 
  Sys.sleep(3)
  
}





```






```{r}

# USAGE --------------------------------------------------------------------------
# Loop through the variables and fetch data for each
years <- c("2009", 
          "2012",
          "2016",
          "2020")

groups <- c("group(DP02)",
            "group(DP03)",
            "group(DP04)",
            "group(DP05)")

for (year in years){
  for (group in groups){
    apifetch_censusdata(group,
                        year,
                        USCB_APIkey)
  }
}



```

